import { DefaultLayout } from "@/components/layout/default-layout";
import type { Metadata } from "next";
import { cookies } from "next/headers";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export type CurrentUser = {
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier": string;
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": string;
  "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": string;
  "AspNet.Identity.SecurityStamp": string;
  "http://schemas.microsoft.com/ws/2008/06/identity/claims/role": string;
  sub: string;
  jti: string;
  iat: number;
  permissions: string[];
  nbf: number;
  exp: number;
  iss: string;
  aud: string;
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const accessToken = cookieStore.get("accessToken");

  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className="font-visby bg-[#f5f5f5]">
        <DefaultLayout accessToken={accessToken}>{children}</DefaultLayout>
      </body>
    </html>
  );
}
